### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by androidmalin** [Piasy/OkBuck#18]
buck install app
Using watchman.
Using buckd.
BUILD FAILED: com/android/dx/command/dexer/Main : Unsupported major.minor version 52.0
[-] PROCESSING BUCK FILES...FINISHED 0.5s [100%]
[-] BUILDING...FINISHED 1.3s [100%] (14/43 JOBS, 13 UPDATED, 30.2% CACHE MISS)

BUILD FAILED: com/android/dx/command/dexer/Main : Unsupported major.minor version 52.0

**Comment by Piasy** [comment]
I think this is neither buck nor OkBuck's problem, you seems use jdk 1.8 to build Android project.

Google your error message to find more details.
