### ISSUE TITLE
用你的配置运行build报错，麻烦帮忙看下是什么问题，谢谢

### ISSUE THREAD

**Issue by liujianying** [Piasy/OkBuck#2]
:MyApplication liujianying$ buck build app
Using buckd.
The following resources were not found when processing app/src/main/res: 
RDotTxtEntry{idType=int, type=string, name=appbar_scrolling_view_behavior, idValue=0x00000000}

java.lang.RuntimeException
java.lang.RuntimeException
        at com.facebook.buck.android.aapt.MiniAapt.execute(MiniAapt.java:154)
        at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:63)
        at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:967)
        at com.facebook.buck.rules.CachingBuildEngine.access$6(CachingBuildEngine.java:950)
        at com.facebook.buck.rules.CachingBuildEngine$1.apply(CachingBuildEngine.java:367)
        at com.facebook.buck.rules.CachingBuildEngine$1.apply(CachingBuildEngine.java:1)
        at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:906)
        at com.google.common.util.concurrent.Futures$1$1.run(Futures.java:635)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

BUILD FAILED: //app:res failed with exit code 1:
generate_resource_ids
[-] PROCESSING BUCK FILES...FINISHED 0.2s [100%]
[-] BUILDING...FINISHED 0.5s [100%] (16/37 JOBS, 5 UPDATED, 13.5% CACHE MISS)
liujianyingdeMacBook-Pro:MyApplication liujianying$

**Comment by Piasy** [comment]
`RDotTxtEntry{idType=int, type=string, name=appbar_scrolling_view_behavior, idValue=0x00000000}`

从这行来看是没有找到resource，你是用了CoordinateLayout吗？我先试着复现一下。

**Comment by liujianying** [comment]
925279861 这个是有qq，可以麻烦加下你么？

**Comment by liujianying** [comment]
现在最新的Studio 1.4版本新建的默认带activity的页面是带CoordinatorLayout的，具体可以看下xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools" android:layout_width="match_parent"
    android:layout_height="match_parent" android:fitsSystemWindows="true"
    tools:context=".MainActivity">

    <android.support.design.widget.AppBarLayout android:layout_height="wrap_content"
        android:layout_width="match_parent" android:theme="@style/AppTheme.AppBarOverlay">

        <android.support.v7.widget.Toolbar android:id="@+id/toolbar"
            android:layout_width="match_parent" android:layout_height="?attr/actionBarSize"
            android:background="?attr/colorPrimary" android:theme="@style/AppTheme.AppBarOverlay"
            app:popupTheme="@style/AppTheme.PopupOverlay" />

    </android.support.design.widget.AppBarLayout>

    <include layout="@layout/content_main" />

    <android.support.design.widget.FloatingActionButton android:id="@+id/fab"
        android:layout_width="wrap_content" android:layout_height="wrap_content"
        android:layout_gravity="end|bottom" android:layout_margin="@dimen/fab_margin"
        android:src="@android:drawable/ic_dialog_email" />

</android.support.design.widget.CoordinatorLayout>

**Comment by Piasy** [comment]
@liujianying 稍等我复现一下

**Comment by Piasy** [comment]
这个是buck的问题。

buck找不到对`appbar_scrolling_view_behavior`的引用，解决办法很简单：

方法1. 在你的module的string.xml里面定义一个string，名字无所谓，但最好别和已有的重复，内容是`"android.support.design.widget.AppBarLayout$ScrollingViewBehavior"`；

方法2. 直接把layout里面对`appbar_scrolling_view_behavior`的引用替换为`"android.support.design.widget.AppBarLayout$ScrollingViewBehavior"`，即：
```xml
app:layout_behavior="android.support.design.widget.AppBarLayout$ScrollingViewBehavior"
```

**Comment by YouCii** [comment]
> ```
> android.support.design.widget.AppBarLayout$ScrollingViewBehavior
> ```

如果是androidx用户, 可以这么写: `com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior`
