### ISSUE TITLE
Missing AIDL support

### ISSUE THREAD

**Issue by vRallev** [Piasy/OkBuck#40]
I have .aidl files in my project, but the corresponding .java files aren't generated.

**Comment by Piasy** [comment]
@vRallev Oh, yes! I'm working on multi-product flavor now, after finishing it I'll add AIDL support.

**Comment by Piasy** [comment]
@vRallev Hello, AIDL support has added since 1.0.0-beta4, this is a minimum support that your .aidl file must locate inside main source set.
