### ISSUE TITLE
Can not figure out sign config, please make sure you have only one sign config in your build.gradle, or set signConfigName in okbuck dsl.

### ISSUE THREAD

**Issue by ASCE1885** [Piasy/OkBuck#52]
when running 
```java
./gradlew okbuck
```

**Comment by Piasy** [comment]
Just specify your sign config name as the error message hint, [like this](https://github.com/Piasy/OkBuck/blob/master/build.gradle#L27).

**Comment by ASCE1885** [comment]
It works, thank you very much!
