### ISSUE TITLE
Gradle build tool 2.0.0

### ISSUE THREAD

**Issue by nbthinkful** [Piasy/OkBuck#59]
I would like to use okbuck in my project, but it does not seem to support gradle build tools 2.0.x

Latest version is found from:-

https://bintray.com/android/android-tools/com.android.tools.build.gradle/2.0.0-alpha7/view

I tried it out, but buck failed to manage to get signing info.

**Comment by Piasy** [comment]
@nbthinkful Yes I have noticed that problem, I'll release a version soon.

**Comment by nbthinkful** [comment]
If you have a snapshot version and you want me to test out, I'll be happy to do so.

**Comment by Piasy** [comment]
@nbthinkful I have just released `0.4.10`, please try it out.

**Comment by nbonavia** [comment]
Tested it today and it worked like a charm. Buck did not build my android project because it did not detect resources that include data binding, but I guess that's buck that needs to be able to build the project.

**Comment by Piasy** [comment]
@nbonavia Yes, buck's official team has claimed that when data binding comes stable, they will work on data binding support.
