### ISSUE TITLE
error after 'buck install flavorName'

### ISSUE THREAD

**Issue by ghuiii** [Piasy/OkBuck#61]
Parse error for build file /Users/ghui/Company/code/app/BUCK:   File "/Users/ghui/Company/code/app/BUCK", line 76, in <module>
    'PUBLIC',
  File "/Users/ghui/Company/code/.buckd/tmp/buck_run.9oqnXu/buck84461324831384572.py", line 119, in invoke
    return self.func(*args, **updated_kwargs)
  File "/Users/ghui/Company/code/-android/-as/.buckd/tmp/buck_run.9oqnXu/buck84461324831384572.py", line 1873, in android_resource
    }, build_env)
  File "/Users/ghui/Company/code/-as/.buckd/tmp/buck_run.9oqnXu/buck84461324831384572.py", line 143, in add_rule
    (rule, build_env.rules[rule_name]))
ValueError: Duplicate rule definition found.  Found {'buck.type': 'android_resource', 'visibility': ['PUBLIC'], 'name': 'res_debug', 'deps': ['//.okbuck/app:aar__library-1.2.8.aar', '//.okbuck/app:aar__recyclerview-v7-21.0.3.aar', '//.okbuck/app:aar__StickyScrollViewItems-1.1.0.aar', '//.okbuck/app:aar__appcompat-v7-22.2.0.aar', '//.okbuck/app:aar__support-v4-22.2.0.aar'], 'hasWhitelistedStrings': None, 'res': 'src/debug/res', 'manifest': None, 'rDotJavaPackage': 'com.test.app', 'assets': None} and {'buck.type': 'android_resource', 'buck.base_path': 'app', 'visibility': ['PUBLIC'], 'name': 'res_debug', 'deps': ['//.okbuck/app:aar__library-1.2.8.aar', '//.okbuck/app:aar__recyclerview-v7-21.0.3.aar', '//.okbuck/app:aar__StickyScrollViewItems-1.1.0.aar', '//.okbuck/app:aar__appcompat-v7-22.2.0.aar', '//.okbuck/app:aar__support-v4-22.2.0.aar'], 'hasWhitelistedStrings': None, 'res': 'src/debug/res', 'manifest': None, 'rDotJavaPackage': 'com.test.app', 'assets': None}

**Comment by Piasy** [comment]
closed

**Comment by ashoykh** [comment]
Anyone have this issue and been able to resolve it?  I'm running into the same issue in my build.

**Comment by kageiit** [comment]
@ashoykh please open a new ticket. Make sure you are on version 0.5.3 (latest)
