### ISSUE TITLE
BUILD FAILED: No rule found when resolving target //app:app in build file //app/BUCK

### ISSUE THREAD

**Issue by cuong0993** [Piasy/OkBuck#63]
Hi.
I had just started learning okbuck. I used your project (just import it, sync and do nothing else) [https://github.com/Piasy/BuckProjectEditDetectDemo](url) and i get this eror when i build 

> 

> root@cuong-K43E:~/Downloads/BuckProjectEditDetectDemo-master# /home/cuong/buck/bin/./buck build app
Not using buckd because watchman isn't installed.
[+] PROCESSING BUCK FILES...0.0s [100%]
BUILD FAILED: No rule found when resolving target //app:app in build file //app/BUCK
Defined in file: /home/cuong/Downloads/BuckProjectEditDetectDemo-master/app/BUCK

I also try with my project too and get same error. 
Please show me how to fix it.
Thank you.

**Comment by Piasy** [comment]
You should run `buck build appDebug` or `buck build appRelease`, these two names `appDebug` and `appRelease` can be found inside `.buckconfig` file generated by OkBuck.

**Comment by eric-townsquared** [comment]
I get this too and my .buckconfig file is empty. My app target's build.gradle file had multiple configurations (release, debug, production, etc), so I expected .buckconfig to reflect that
