### ISSUE TITLE
There is one problem.

### ISSUE THREAD

**Issue by jansonjoan** [Piasy/OkBuck#65]
Incremental java compilation is an incubating feature.
:okbuckClean
:FashionMii:okbuckClean
:FashionMii:okbuck
:okbuck
==========>> overwrite mode is toggle on <<==========
:okbuck FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':okbuck'.
> resPackage key-value pair must be set for sub project FashionMii in your root project build.gradle file

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by Piasy** [comment]
As the error message said: 
> resPackage key-value pair must be set for sub project FashionMii in your root project build.gradle file

You can see the [explanation part of README](https://github.com/Piasy/OkBuck#explanations).

**Comment by Piasy** [comment]
closed
