### ISSUE TITLE
Okbuck fails to process projects with "-" in their name

### ISSUE THREAD

**Issue by kageiit** [Piasy/OkBuck#68]
Easy way to reproduce is to rename "anotherapp" to "another-app" and try to run `./gradlew okbuck` on master

**Comment by Piasy** [comment]
Yes I know this problem, maybe I delete the note for this problem in some commit.

**Comment by kageiit** [comment]
Is there any solution to this? I tried to tackle solving this by making some changes, but if you already know about it, it would be great to understand why it breaks so I have a better idea to fix it if possible

**Comment by Piasy** [comment]
Sorry that it's months before, I forget the reason...

Could you replace your `-` with `_` in your module name?

**Comment by kageiit** [comment]
I know removing "-" or replacing it with "_" fixes it, but I dont think its something a gradle plugin should force users to do. I will look at whats causing this problem, because I was able to setup buck for projects with "-" in module name manually before, but the auto generated version from okbuck plugin have issues.

I guess it is an issue with Okbuck and not really buck's

**Comment by kageiit** [comment]
I think I found a solution to the problem. The issue is with how OkBuck is relying on the aar name to determine the flavor and variant.

There is a better way to determine this without depending on splitting the aar file name by "-". That seems to be the problem. I will open a PR with the fix.

**Comment by Piasy** [comment]
@kageiit You are definitely right! I have to admit that the way I used to determine flavor and variant is really a poor one...

**Comment by Piasy** [comment]
It's inside [`FileUtil.groovy`](https://github.com/Piasy/OkBuck/blob/f01ba56a7f375e1762a545222c7b101b36587c5d/buildSrc%2Fsrc%2Fmain%2Fgroovy%2Fcom%2Fgithub%2Fpiasy%2Fokbuck%2Fhelper%2FFileUtil.groovy#L99), and it utilize several naming convention, which may cause other problems too, e.g. [dependency duplication detection](https://github.com/Piasy/OkBuck/blob/f01ba56a7f375e1762a545222c7b101b36587c5d/buildSrc%2Fsrc%2Fmain%2Fgroovy%2Fcom%2Fgithub%2Fpiasy%2Fokbuck%2Fhelper%2FFileUtil.groovy#L63), could you please share your idea before fix it? I'd like to know the solution ASAP :)

**Comment by kageiit** [comment]
I have another solution for the dependency duplication detection which i will open a separate PR for once the "-" one merges
